version: '3'
services:
  truenative:
    container_name: truenative
    build: 
      context: ./truenative
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      SECRET_TOKEN: d5f14860-f674-4248-be61-18bed307a49f
    restart: always
    networks:
      - app_net
  
  users_db:
    container_name: users_db
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - user_net   
  
  users:
    container_name: users
    build: 
      context: ./users
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3001:3000"
    environment:
      DB_NAME: usersdb
      DB_HOST: users_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      USERS_PATH: "http://users:3000"
      TRUENATIVE_PATH: "http://truenative:3000"
      SECRET_TOKEN: "d5f14860-f674-4248-be61-18bed307a49f"
      SEND_EMAIL_PATH: "https://us-central1-misw-app-nativas-nube.cloudfunctions.net/function-send-mail"
    restart: always
    networks:
      - user_net 
      - app_net
    depends_on:
      - users_db

  rf006_db:
    container_name: rf006_db  
    image: postgres:14.1-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: rf006db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - rf006_net 

  rf006:
    container_name: rf006
    build: 
      context: ./rf006
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3002:3000"
    environment:
      DB_NAME: rf006db
      DB_HOST: rf006_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      USERS_PATH: "http://users:3000"
      TRUENATIVE_PATH: "http://truenative:3000"
      TRUENATIVE_TOKEN: d5f14860-f674-4248-be61-18bed307a49f
      SECRET_TOKEN: "d5f14860-f674-4248-be61-18bed307a49f"
      SEND_EMAIL_PATH: "https://us-central1-misw-app-nativas-nube.cloudfunctions.net/function-send-mail"
    restart: always
    networks:
      - rf006_net
      - app_net
    depends_on:
      - rf006_db
      - users
      - truenative

  rf006_poll:
    container_name: rf006_poll
    build: 
      context: ./rf006_poll
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3003:3000"
    environment:
      RF006_PATH: "http://rf006:3000"
      TRUENATIVE_PATH: "http://truenative:3000"
      TRUENATIVE_TOKEN: "d5f14860-f674-4248-be61-18bed307a49f"
      EMAIL_TOKEN: "d5f14860-f674-4248-be61-18bed307a4a0"
      USERS_PATH: "http://users:3000"
      SEND_EMAIL_PATH: "https://us-central1-misw-app-nativas-nube.cloudfunctions.net/function-send-mail"
    restart: always
    networks:
      - rf006_net
      - app_net
    depends_on:
      - rf006

  sendmail:
    container_name: sendmail
    build: 
      context: ./sendmail
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3004:3000"
    environment:
      SECRET_TOKEN: d5f14860-f674-4248-be61-18bed307a49f
    restart: always
    networks:
      - app_net

  nginx_proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx_proxy
    restart: always
    networks:
      - app_net
    depends_on:
      - truenative
      - users
      - rf006
      - rf006_poll
      - sendmail

  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    networks:
      - app_net   

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  app_net:
    driver: bridge  
  user_net:
    driver: bridge
  rf006_net:
    driver: bridge