version: '3'
services:
  users:
    container_name: users
    build: 
      context: ./users
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:5000"
    environment:
      DB_NAME: usersdb
      DB_HOST: users_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - user_net 
      - app_net

  users_db:
    container_name: users_db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - user_net 

  posts:
    container_name: posts
    build: 
      context: ./posts
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:5000"
    environment:
      DB_NAME: postsdb
      DB_HOST: posts_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    restart: always
    networks:
      - post_net 
      - app_net

  posts_db:
    container_name: posts_db  
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - post_net 

  offers:
    container_name: offers
    build: 
      context: ./offers
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3003:5000"
    environment:
      DB_NAME: offersdb
      DB_HOST: offers_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    restart: always
    networks:
      - offer_net 
      - app_net

  offers_db:
    container_name: offers_db  
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: offersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    networks:
      - offer_net 

  routes:
    container_name: routes
    build: 
      context: ./routes
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3002:5000"
    environment:
      DB_NAME: routesdb
      DB_HOST: routes_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    restart: always
    networks:
      - route_net 
      - app_net

  routes_db:
    container_name: routes_db  
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: routesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    networks:
      - route_net 

networks:
  app_net:
    driver: bridge
  user_net:
    driver: bridge
  offer_net:
    driver: bridge
  route_net:
    driver: bridge    
  post_net:
    driver: bridge          